#pragma once

//
//	Pixel font data generated by bitfontmaker2 - https://www.pentacom.jp/pentacom/bitfontmaker2/
//                                                            Book Font is Owls N' Ink by DubzyWubzyUbzy. Slightly modified.
//                                                            Record Player font is Agency FB, also modified.
//	https://www.pentacom.jp/pentacom/bitfontmaker2/gallery/?id=556
//
//  Keys in dict are ASCII character codes.
//  The array associated with a character is a list of rows in its bitmap image.
//  Each number is a bit field representing which pixels are filled or blank in that row.
//  When converted to a binary string, 1s are filled pixels, 0s are blank.

#include <QList>
#include <QHash>
#include <QPainter>
#include "font.h"

// Left-adjusted drawing routine
void draw_text_l(const Font &font, QPainter &painter, QPoint pos, QString text, QColor color) {
    int x = pos.x();
    int y = pos.y();
    int bearing_x = 2;
    int space_size = 5;
    painter.setPen(color);
    for (QChar c : text) {
        int size = 0;
        if (font.contains(c.unicode())) {
            QList<int> bitmap = font.value(c.unicode());
            for (int cy = 0; cy < 16; cy++) {
                int row = bitmap[cy];
                for (int cx = 0; cx < 16; cx++) {
                    if (row & (0b1 << cx)) {
                        painter.drawPoint(cx-bearing_x+x, cy+y);
                        size = std::max(size, cx-bearing_x);
                    }
                }
            }
        }
        x = c.unicode() != 32 ? x+size+2 : x+space_size;
    }
}

// Right-adjusted drawing routine
void draw_text_r(const Font &font, QPainter &painter, QPoint pos, QString text, QColor color) {
    int bearing_x = 2;
    int space_size = 5;
    int total_size = -1;
    painter.setPen(color);
    for (QChar c : text) {
        int size = 0;
        if (font.contains(c.unicode())) {
            QList<int> bitmap = font.value(c.unicode());
            for (int cy = 0; cy < 16; cy++) {
                int row = bitmap[cy];
                for (int cx = 0; cx < 16; cx++) {
                    if (row & (0b1 << cx)) {
                        size = std::max(size, cx-bearing_x);
                    }
                }
            }
        }
        total_size = c.unicode() != 32 ? total_size+size+2 : total_size+space_size;
    }
    int x = pos.x() - total_size;
    int y = pos.y();
    for (QChar c : text) {
        int size = 0;
        if (font.contains(c.unicode())) {
            QList<int> bitmap = font.value(c.unicode());
            for (int cy = 0; cy < 16; cy++) {
                int row = bitmap[cy];
                for (int cx = 0; cx < 16; cx++) {
                    if (row & (0b1 << cx)) {
                        painter.drawPoint(cx-bearing_x+x, cy+y);
                        size = std::max(size, cx-bearing_x);
                    }
                }
            }
        }
        x = c.unicode() != 32 ? x+size+2 : x+space_size;
    }
}
